name: BankOps CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Spring Boot app
        working-directory: backend/bankops-backend
        run: ./mvnw clean package -DskipTests

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build React app
        working-directory: frontend/bankops-frontend
        run: |
          npm install
          npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push backend image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/bankops-backend:${{ github.sha }} ./backend/bankops-backend
          docker push $ECR_REGISTRY/bankops-backend:${{ github.sha }}

      - name: Build and push frontend image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/bankops-frontend:${{ github.sha }} ./frontend/bankops-frontend
          docker push $ECR_REGISTRY/bankops-frontend:${{ github.sha }}

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name bankops-cluster --region ap-south-1
          kubectl set image deployment/backend backend=$ECR_REGISTRY/bankops-backend:${{ github.sha }}
          kubectl set image deployment/frontend frontend=$ECR_REGISTRY/bankops-frontend:${{ github.sha }}
          kubectl rollout status deployment/backend
          kubectl rollout status deployment/frontend